### ISSUE TITLE
等着，终于开了issue

### ISSUE THREAD

**Issue by zasl** [lixingcong/dnsmasq-openwrt#1]
麻烦请看一下这些错误我应该如何解决？debian8.5 x64，在此环境下编译过ssr。另外请问如果要升级，我看官方最新是2.76，我是否只需要更改m文件的版本号就可以了？

/root/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.15/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
 #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
  ^
mips-openwrt-linux-musl-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap /root/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.15/dnsmasq-full/dnsmasq-2.75:dnsmasq-2.75 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -ffunction-sections -fdata-sections -DHAVE_DNSSEC     -DVERSION='"2.75"'          -c dnssec.c  
In file included from dnsmasq.h:85:0,
                 from dnssec.c:18:
/root/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.15/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
 #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
  ^
dnssec.c:22:24: fatal error: nettle/rsa.h: No such file or directory
compilation terminated.
/root/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.15/dnsmasq-full/dnsmasq-2.75/Makefile:156: recipe for target 'dnssec.o' failed
make[4]: **\* [dnssec.o] Error 1
make[4]: Leaving directory '/root/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.15/dnsmasq-full/dnsmasq-2.75/src'
Makefile:82: recipe for target 'all' failed
make[3]: **\* [all] Error 2
make[3]: Leaving directory '/root/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.15/dnsmasq-full/dnsmasq-2.75'
Makefile:151: recipe for target '/root/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.15/dnsmasq-full/dnsmasq-2.75/.built' failed
make[2]: **\* [/root/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.15/dnsmasq-full/dnsmasq-2.75/.built] Error 2
make[2]: Leaving directory '/root/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64/package/dnsmasq'
package/Makefile:196: recipe for target 'package/dnsmasq/compile' failed
make[1]: **\* [package/dnsmasq/compile] Error 2
make[1]: Leaving directory '/root/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64'
/root/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64/include/toplevel.mk:185: recipe for target 'package/dnsmasq/compile' failed
make: **\* [package/dnsmasq/compile] Error 2
root@debian:~/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.15.Linux-x86_64#

**Comment by lixingcong** [comment]
你openwrt版本是trunk版的吧？我是在op 15.05.1版的编译通过。。。

我也不太懂这个，我是fork原作者[@a65555](https://github.com/aa65535/openwrt-dnsmasq)的项目的。

既然是trunk版的，不需要编译了，内置的dnsmasq的版本应该比较新

**Comment by lixingcong** [comment]
如果升级，可以改版本号然后删掉那几个patch文件（针对旧版本的patch）

这个项目很老了，不再维护。

**Comment by zasl** [comment]
是的，我是trunk版本，所带的版本是2.76的版本，但是不知道是否增加了你这个功能。

**Comment by lixingcong** [comment]
dnsmasq从2.73版本开始具有以下功能

--ignore-address 选项, 忽略指定的 IP, 过滤虚假DNS答复
--min-cache-ttl 选项, 可设置 DNS缓存最小有效期

**Comment by zasl** [comment]
好的，非常感谢
