### ISSUE TITLE
可以这样匹配吗

### ISSUE THREAD

**Issue by moorn** [lixingcong/dnsmasq-openwrt#2]
server=/:.*google.*:/127.0.0.1#5353
ipset=/:.*google.*:/gfwlis

**Comment by moorn** [comment]
address=/:.*ads.*:/0.0.0.0

**Comment by lixingcong** [comment]
暂时没有做ipset功能，你可以用一个带有ipset功能的版本：

https://github.com/cuckoohello/dnsmasq-regex
