### ISSUE TITLE
Question about NFTSet regex support

### ISSUE THREAD

**Issue by ILMAZ13** [lixingcong/dnsmasq-openwrt#4]
Hi) I really like your project and what you've done.
I'm going to switch to the last version of OpenWrt, where is no ipset support anymore. But nftset works by default there.

Will wour version support regex for NFTSets or does it already work?

**Comment by lixingcong** [comment]
No plan for this.

**Comment by ILMAZ13** [comment]
Will you check my PR and accept it, if I send it to you? I'm too bad in C or C++, but I'll try)

**Comment by lixingcong** [comment]
This repo is downstream of dnsmasq-regex. Nftables patch pull request is welcome for upstream dnsmasq-regex repo: https://github.com/lixingcong/dnsmasq-regex

**Comment by lixingcong** [comment]
The offical  [dnsmasq v2.87](https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commitdiff;h=47aefca5e405b4b6627ef952fdc42e61b1baa770;hp=981fb037102306a4ca683f14c8469db4d5e27233) supports nftables set.

But openwrt 22.03 is shipped with an out-of-dated version v2.86. It is easy to port regex support to nftables.

Wait for next release of OpenWrt.
