### ISSUE TITLE
15.05, 17.01 没有生效

### ISSUE THREAD

**Issue by zhang-ray** [lixingcong/dnsmasq-openwrt#5]
感谢大佬的辛勤工作。

发现正则相关的补丁没有打到 15.05 17.01,  分支上面 😄

**Comment by lixingcong** [comment]
15.05和17.01太远古了，不维护了。

原ipk是直接从旧的dnsmasq-regex克隆下来，直接编译ipk的，现在dnsmasq-regex仓库最旧的版本已经是2.80，比15.05新很多版本，不做backport了。

**Comment by zhang-ray** [comment]
> 15.05和17.01太远古了，不维护了。
> 
> 原ipk是直接从旧的dnsmasq-regex克隆下来，直接编译ipk的，现在dnsmasq-regex仓库最旧的版本已经是2.80，比15.05新很多版本，不做backport了。

好的👌了解了。 不过我已经移植到 17.01 过去了，差别不太大😊
